name: NSE High-Delivery Scan (12:00 PM IST, Mon–Fri)

on:
  schedule:
    # GitHub cron is UTC. 10:00 IST == 04:30 UTC. Mon–Fri only.
    - cron: "30 6 * * 1-5"
  workflow_dispatch:

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  TZ: Asia/Kolkata
  # Tune async concurrency (your script supports --use-async & --concurrency)
  NSE_CONCURRENCY: "2"
  CI: true
  

jobs:
  run-screener:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    concurrency:
      group: nse-daily-fast
      cancel-in-progress: false

    # Map secrets to job env so steps (and if: expressions) can use env.*
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12" 
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare folders (cache/output)
        run: |
          mkdir -p cache output

      - name: Check Telegram secrets present
        if: ${{ env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != '' }}
        run: echo "Telegram secrets are set."

      - name: Run fast.py (async turbo)
        # Secrets already provided via job-level env
        run: |
          set -e
          python fast.py \
            --use-async 
        # (all flags above match your defaults; kept here for explicitness)

      - name: Upload Excel results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.run_id }}
          path: output/*.xlsx
          if-no-files-found: warn
          retention-days: 14

      - name: Upload logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}
          path: |
            **/*.log
          if-no-files-found: ignore
          retention-days: 7
